import { spawn } from "node:child_process";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const BASE = "http://127.0.0.1:4173";
const OUT = path.resolve("visual-audit-v2-round1-global-fixes");
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

class Cdp {
  constructor(url) { this.ws = new WebSocket(url); this.id = 0; this.pending = new Map(); this.events = new Map(); }
  async open() { await new Promise((resolve, reject) => { this.ws.addEventListener("open", resolve, { once: true }); this.ws.addEventListener("error", reject, { once: true }); }); this.ws.addEventListener("message", ({ data }) => { const m = JSON.parse(data); if (m.id) { const p = this.pending.get(m.id); if (!p) return; this.pending.delete(m.id); clearTimeout(p.timer); m.error ? p.reject(new Error(m.error.message)) : p.resolve(m.result); return; } for (const fn of this.events.get(m.method) || []) fn(m.params); }); }
  send(method, params = {}) { const id = ++this.id; return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(id); reject(new Error(`Timed out: ${method}`)); }, 15000); this.pending.set(id, { resolve, reject, timer }); this.ws.send(JSON.stringify({ id, method, params })); }); }
  on(method, fn) { this.events.set(method, [...(this.events.get(method) || []), fn]); }
  once(method) { return new Promise((resolve) => this.on(method, resolve)); }
  close() { this.ws.close(); }
}
async function launch(port) { const profile = await mkdtemp(path.join(os.tmpdir(), `round1-${port}-`)); const chrome = spawn(CHROME, ["--headless=new", "--no-sandbox", "--disable-gpu", "--hide-scrollbars", "--no-first-run", `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, "about:blank"], { stdio: "ignore", windowsHide: true }); for (let i = 0; i < 60; i++) { try { const list = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json(); const target = list.find((item) => item.type === "page"); if (target) return { chrome, target }; } catch {} await sleep(100); } chrome.kill(); throw new Error("Chrome target unavailable"); }
async function evaluate(c, expression) { const r = await c.send("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error(r.exceptionDetails.text || "Runtime evaluate failed"); return r.result.value; }
async function shot(c, name, full = false) { const r = await c.send("Page.captureScreenshot", { format: "png", fromSurface: true, captureBeyondViewport: full }); await writeFile(path.join(OUT, name), Buffer.from(r.data, "base64")); }
async function setup(c, width, height, mobile, reduced) { await Promise.all([c.send("Page.enable"), c.send("Runtime.enable"), c.send("Network.enable"), c.send("Log.enable"), c.send("Emulation.setDeviceMetricsOverride", { width, height, mobile, screenWidth: width, screenHeight: height, deviceScaleFactor: 1 }), c.send("Emulation.setEmulatedMedia", { media: "screen", features: reduced ? [{ name: "prefers-reduced-motion", value: "reduce" }] : [] })]); }
async function load(c, url, width, height, mobile, reduced = false, settle = 900) { await setup(c, width, height, mobile, reduced); const loaded = c.once("Page.loadEventFired"); await c.send("Page.navigate", { url: `${BASE}${url}` }); await loaded; await sleep(reduced ? Math.min(150, settle) : settle); }
async function revealLazy(c) { const { height, total } = await evaluate(c, "({height:innerHeight,total:document.body.scrollHeight})"); for (let y=0; y<total; y+=Math.max(360,height*.8)) { await evaluate(c, `window.scrollTo(0,${Math.round(y)})`); await sleep(80); } await evaluate(c, "window.scrollTo(0,0)"); await sleep(250); }
function collect(c, issues) { c.on("Runtime.exceptionThrown", ({ exceptionDetails }) => issues.js.push(exceptionDetails.text || "Runtime exception")); c.on("Runtime.consoleAPICalled", ({ type, args }) => { if (type === "error" || type === "assert") issues.js.push(args.map((a) => a.value || a.description || "console error").join(" ")); }); c.on("Network.responseReceived", ({ response }) => { if (response.status === 404) issues.notFound.push(response.url); }); c.on("Network.loadingFailed", ({ type, errorText }) => { if (type === "Image") issues.images.push(errorText); }); }
async function metrics(c) { return evaluate(c, `(() => ({ overflow: Math.max(0, document.documentElement.scrollWidth-document.documentElement.clientWidth, document.body.scrollWidth-document.documentElement.clientWidth), images: [...document.images].filter((i)=>!i.closest('details:not([open])')&&(!i.complete||i.naturalWidth===0)).map((i)=>i.currentSrc||i.src), header: (()=>{const h=document.querySelector('header');if(!h)return null;const s=getComputedStyle(h);return {height:Math.round(h.getBoundingClientRect().height),zIndex:s.zIndex,background:s.backgroundColor,opacity:s.opacity,position:s.position}})(), anchors:[...document.querySelectorAll('main [id]')].map((n)=>({id:n.id,margin:getComputedStyle(n).scrollMarginTop})) }))()`); }
async function checkPage({ key, url, width, height, mobile, port, hero = false, reduced = false }) { const { chrome, target } = await launch(port); const c = new Cdp(target.webSocketDebuggerUrl); const issues = { js: [], images: [], notFound: [] }; try { await c.open(); collect(c, issues); await load(c, url, width, height, mobile, reduced); if (hero) await shot(c, `${key}-${mobile ? "mobile" : "desktop"}-hero.png`); await revealLazy(c); await shot(c, `${key}-${mobile ? "mobile" : "desktop"}-full.png`, true); const links = await evaluate(c, "[...new Set([...document.querySelectorAll('a[href]')].map((a)=>a.href))]"); const interaction = await evaluate(c, `(() => { const result={linkCount:${0}}; const b=document.querySelector('.menu-button'); if(b){b.click();result.menu={kind:'button',expanded:b.getAttribute('aria-expanded'),visible:getComputedStyle(document.querySelector('.mobile-nav')).visibility};b.click();} const d=document.querySelector('.case-mobile-nav'); if(d){d.open=true;result.menu={kind:'details',open:d.open};d.open=false;} const a=document.querySelector('details.appendix,details.qfc-appendix,details.clj-appendix'); if(a){a.open=true;result.appendix={present:true,open:a.open,images:a.querySelectorAll('img').length};a.open=false;} return result; })()`.replace("linkCount:0", `linkCount:${links.length}`)); const anchorInfo = await evaluate(c, "(()=>{const a=document.querySelector('header nav a[href^=\"#\"]');if(!a)return null;const id=a.getAttribute('href').slice(1);a.click();return {id};})()"); await sleep(500); const anchor = anchorInfo ? await evaluate(c, `(()=>{const t=document.getElementById(${JSON.stringify(anchorInfo.id)}),h=document.querySelector('header');return {id:${JSON.stringify(anchorInfo.id)},targetTop:Math.round(t.getBoundingClientRect().top),headerBottom:Math.round(h.getBoundingClientRect().bottom),visible:t.getBoundingClientRect().top>=h.getBoundingClientRect().bottom-2};})()`) : null; await evaluate(c, "window.scrollTo(0, Math.min(document.body.scrollHeight-innerHeight, innerHeight*1.2))"); await sleep(250); await shot(c, `${key}-${mobile ? "mobile" : "desktop"}-header-over-content.png`); return { viewport:{width,height}, ...await metrics(c), anchor, interaction, links:links.length, issues }; } finally { c.close(); chrome.kill(); } }
async function firstLoadHero() { const { chrome, target } = await launch(11200); const c = new Cdp(target.webSocketDebuggerUrl); try { await c.open(); await load(c, "/cases/quiet-fitness-cabin.html", 1440, 900, false, false, 10); await shot(c, "case02-hero-first-load.png"); return { visible: await evaluate(c, "[...document.querySelectorAll('.qfc-hero h1,.qfc-hero__copy>p,.qfc-hero__visual')].every((n)=>getComputedStyle(n).opacity!=='0'&&n.getBoundingClientRect().height>0)"), motionReady: await evaluate(c, "document.documentElement.classList.contains('qfc-motion-ready')") }; } finally { c.close(); chrome.kill(); } }
async function evidenceShot() { const { chrome, target } = await launch(11201); const c = new Cdp(target.webSocketDebuggerUrl); try { await c.open(); await load(c, "/cases/should-i-work-out-today.html", 1440, 900, false); await evaluate(c, "document.querySelectorAll('#decisions .case-motion-item').forEach((n)=>n.classList.add('is-visible'));document.querySelector('.correction-evidence').scrollIntoView({block:'center'})"); await sleep(900); await shot(c, "case01-evidence-correction-fixed.png"); } finally { c.close(); chrome.kill(); } }
async function main() { const pages = [
  ["homepage","/",1440,900,false,11191,false], ["homepage","/",390,844,true,11192,false],
  ["case01","/cases/should-i-work-out-today.html",1440,900,false,11193,false], ["case01","/cases/should-i-work-out-today.html",390,844,true,11194,false],
  ["case02","/cases/quiet-fitness-cabin.html",1440,900,false,11195,true], ["case02","/cases/quiet-fitness-cabin.html",390,844,true,11196,true],
  ["case03","/cases/connected-long-journey.html",1440,900,false,11197,false], ["case03","/cases/connected-long-journey.html",390,844,true,11198,false],
  ]; const results=[]; for(const p of pages){console.log(`QA ${p[0]} ${p[2]}x${p[3]}`);results.push(await checkPage({key:p[0],url:p[1],width:p[2],height:p[3],mobile:p[4],port:p[5],hero:p[6]}));} const reduced=await checkPage({key:"case02-reduced",url:"/cases/quiet-fitness-cabin.html",width:390,height:844,mobile:true,port:11199,hero:true,reduced:true}); const firstLoad=await firstLoadHero(); await evidenceShot(); const report={results,reduced,firstLoad,generatedAt:new Date().toISOString()}; await writeFile(path.join(OUT,"qa-results.json"),JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2)); }
const server=spawn("python",["-m","http.server","4173","--bind","127.0.0.1","--directory","dist"],{stdio:"ignore",windowsHide:true}); await sleep(1000); main().catch((e)=>{console.error(e);process.exitCode=1;}).finally(()=>server.kill());
