import { spawn } from "node:child_process";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
const chrome = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", url = "http://127.0.0.1:4173/cases/should-i-work-out-today.html", out = path.resolve("visual-audit-v2-case01-static-r2"), sleep = (n) => new Promise((r) => setTimeout(r, n));
class Cdp { constructor(ws) { this.ws=new WebSocket(ws); this.id=0; this.pending=new Map(); this.listeners=new Map(); } async open() { await new Promise((ok,no)=>{this.ws.addEventListener("open",ok,{once:true});this.ws.addEventListener("error",no,{once:true});}); this.ws.addEventListener("message",(e)=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);return;}(this.listeners.get(m.method)||[]).forEach((fn)=>fn(m.params));}); } send(method,params={}) { const id=++this.id;return new Promise((ok,no)=>{const t=setTimeout(()=>{this.pending.delete(id);no(new Error(method));},20000);this.pending.set(id,{resolve:(x)=>{clearTimeout(t);ok(x);},reject:no});this.ws.send(JSON.stringify({id,method,params}));}); } once(method) { return new Promise((ok)=>this.listeners.set(method,[...(this.listeners.get(method)||[]),ok])); } close(){this.ws.close();} }
async function launch(port) { const profile=await mkdtemp(path.join(os.tmpdir(),"case01-r2-"));const process=spawn(chrome,["--headless=new","--no-sandbox","--disable-gpu","--hide-scrollbars","--remote-allow-origins=*",`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,"about:blank"],{stdio:"ignore",windowsHide:true});for(let i=0;i<60;i++){try{const pages=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();const page=pages.find((x)=>x.type==="page");if(page)return{process,page};}catch{}await sleep(100);}throw new Error("Chrome unavailable"); }
async function value(c,e){const r=await c.send("Runtime.evaluate",{expression:e,awaitPromise:true,returnByValue:true});return r.result.value;} async function shot(c,name,selector){const clip=await value(c,`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:Math.max(0,r.left),y:r.top+scrollY,width:r.width,height:r.height,scale:1}})()`);const r=await c.send("Page.captureScreenshot",{format:"png",captureBeyondViewport:true,clip});await writeFile(path.join(out,name),Buffer.from(r.data,"base64"));}
async function load(c,width,height,mobile){await Promise.all([c.send("Page.enable"),c.send("Runtime.enable"),c.send("Network.enable"),c.send("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile})]);const done=c.once("Page.loadEventFired");await c.send("Page.navigate",{url});await done;await sleep(350);const h=await value(c,"document.body.scrollHeight");for(let y=0;y<h;y+=Math.max(400,height*.8)){await value(c,`scrollTo(0,${y})`);await sleep(70);}await value(c,"scrollTo(0,0)");await sleep(250);}
await mkdir(out,{recursive:true});const {process,page}=await launch(9251),c=new Cdp(page.webSocketDebuggerUrl),errors=[],failed=[];await c.open();c.listeners.set("Runtime.exceptionThrown",[(e)=>errors.push(e.exceptionDetails?.text||"runtime")]);c.listeners.set("Network.loadingFailed",[(e)=>failed.push(e.errorText||"network")]);try{await load(c,1440,960,false);await shot(c,"case01-r2-critical-decisions.png","#decisions");await shot(c,"case01-r2-core-experience.png","#experience");const desktop=await value(c,"({overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),images:[...document.images].filter(i=>i.currentSrc&&i.naturalWidth===0).length,critical:document.querySelector('.critical-title').innerText,experience:document.querySelector('.experience-title').innerText})");await load(c,390,844,true);await shot(c,"case01-r2-mobile-critical.png","#decisions");await shot(c,"case01-r2-mobile-core.png","#experience");const mobile=await value(c,"({overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),images:[...document.images].filter(i=>i.currentSrc&&i.naturalWidth===0).length,phases:document.querySelectorAll('.experience-phase').length})");await writeFile(path.join(out,"audit-results.json"),JSON.stringify({desktop,mobile,runtimeErrors:errors,networkFailures:failed},null,2));console.log(JSON.stringify({desktop,mobile,runtimeErrors:errors.length,networkFailures:failed.length},null,2));}finally{c.close();process.kill();}
